SMS/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.contrib.auth import views as auth_views 
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polling.urls')),
    path('register/', user_views.register, name= 'register'), 
    path('profile/', user_views.profile, name= 'profile'),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'), name='login'), 
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name ='logout'), 
    
]
if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polling/urls.py
from django.urls import path 
from .import views

app_name = 'polling'
urlpatterns = [

        path('', views.IndexView.as_view(), name='index'), 
        path('<int:pk>/results/', views.ResultsView.as_view(), name = 'results'),
        path('<int:pk>/', views.DetailView.as_view(), name='details'), 
        path ('<int:question_id>/vote/', views.vote, name='vote'), 

]

polling/models.py
from django.db import models
from django.utils import timezone 
import datetime 

class Question(models.Model): 
    question_text = models.CharField(max_length=500)
    pub_date = models.DateTimeField('date publish')
    def __str__(self): 
        return self.question_text
    def recent_changes(self): 
        return self.pub_date >=timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model): 
   
    questions = models.ForeignKey(Question, on_delete=models.CASCADE) 
    
    choice_text = models.CharField(max_length=150) 
    
    votes = models.IntegerField(default=0)
    
    def __str__(self): 
        return self.choice_text

users/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self): 
        return f'{self.user.username} Profile'

users/forms.py
from django import forms 
from django.contrib.auth.models import User 
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class UserRegisterForm(UserCreationForm): 
    email = forms.EmailField()

    class Meta: 
        model = User 
        fields = ['username', 'email', 'password1', 'password2']
    
class UserUpdateForm(forms.ModelForm): 
    email = forms.EmailField()

    class Meta: 
        model = User 
        fields = ['username', 'email']

class ProfileUpdateForm(forms.ModelForm): 
    class Meta: 
        model = Profile 
        fields = ['image'] 

polling/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect 
from django.template import loader
from django.views import generic 
from django.urls import reverse
from .models import Choice, Question 
import json 
from django.db.models import Count, Q 

class IndexView (generic.ListView): 
    template_name = 'polling/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self): 
        return Question.objects.order_by('-pub_date')[:5]
    
    #latest_question_list = Question.objects.order_by('-pub_date')[:5]
   # template = loader.get_template('polling/index.html')
    
    #context = { 'latest_question_list': latest_question_list, }
    
    #output = ', '.join([q.question_text for q in latest_question_list])
    
    #return render(request, 'polling/index.html', context) 


class DetailView (generic.DetailView): 
    model = Question
    template_name = 'polling/detail.html'
    #question = get_object_or_404(Question, pk=question_id)
    #return render(request, 'polling/detail.html', {'question':question} )

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polling/result.html'
#def results (request, question_id): 
    #question = get_object_or_404(Question, pk=question_id)
    #return render (request, 'polling/result.html', {'question': question})


def vote (request, question_id): 
    question = get_object_or_404(Question, pk=question_id)
    try: 
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist): 
        return render (request, 'polling/detail.html', {'question': question, 'error_message': "You didn't select a choice.",})
    # returns an HttpResponseREdirect after succesful dealing with post data. THis prevents data from being posted twice if a user hits the back button. 
   
    else: 
        selected_choice.votes +=1 
        selected_choice.save()
        return HttpResponseRedirect(reverse('polling:results', args = (question.id,)))

users/views.py
from django.shortcuts import render, redirect 
from django.contrib import messages 
from django.contrib.auth.decorators import login_required 
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm  

def register(request): 
    if request.method == 'POST': 
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')    
            messages.success(request, f'your account has been created! you can now login {username}')
            return redirect ('login')
    else: 
        form = UserRegisterForm()
    return render (request, 'users/register.html', {'form': form })
    
@login_required 
def profile(request): 
    if request.method == 'POST': 
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile) 
        if u_form.is_valid() and p_form.is_valid(): 
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated! You are now able to  log in')
            return redirect('profile') 

    else: 
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile) 


    context = {
                'u_form' : u_form, 
                'p_form' : p_form,
        }    
    return render (request, 'users/profile.html', context)

polling/templates/polling/detail.html
<h1> {{ question.question_text }}</h1>
{% if error_message %} <p> <strong> {{ error_message }}</strong> </p>{% endif %}

<form action= "{% url 'polling:vote' question.id %}" method="post"> 
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type= "radio" name="choice" id="choice {{ forloop.counter }}" value="{{choice.id }}"> 
    <label for="choice {{ forloop.counter }}"> {{ choice.choice_text }} </label><br> 
{% endfor %}
<input type="submit" value="Vote"> 
</form>

polling/templates/polling/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polling/style.css' %}"> 

{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %} 
         <li>  <a href="{% url 'polling:details' question.id %}"> {{ question.question_text }}</a> </li>

        {% endfor %}
           
    </ul>

{% else %}
    <p> No polls are available. </p>
{% endif %}

polling/templates/polling/result.html
<h1> {{ question.question_text  }}</h1>

<ul> 
{% for choice in question.choice_set.all %}
      <li> {{ choice.choice_text }} >> {{ choice.votes }} vote{{ choice.votes|pluralize }} </li>
{% endfor %}
</ul>

<a href="{% url 'polling:details' question.id %}"> Vote again? </a>  



<canvas id="myChart" width= 500 height= 500 ></canvas>
<script src = "https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script> 
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"> </link> 
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script>  
      var data=[];
      // Experiments
      labels = [] 
      data = []
      console.log('{% for choice in question.choice_set.all %}')
      console.log('{{ choice.choice_text }}')
      console.log('{{ choice.votes }}')
      labels.push('{{choice.choice_text}}')
      data.push('{{ choice.votes }}')
      console.log('{% endfor %}')
     console.log(labels)
     console.log(data)


      var ctx = document.getElementById('myChart').getContext('2d');
      var myChart = new Chart(ctx, {
      type: 'bar',
      data: { 
            labels: labels, 
            datasets: [ {
                  label:'Votes', 
                  data: data, 
                  backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)'
                  ], 
                  borderColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)'
                  ], 
                 /* borderWidth: 1 */
            }]
      }, 
      options: {
            title: {
                  display: true, 
                  text: 'Results of your survey'
            }, 
            responsive: false,
            scales: {
                  yAxes: [{
                        ticks: { 
                              beginAtZero: true
                        }
                  }]
            }
      } 
});   
</script>

users/templates/users/login.html
{% extends "polling/admin/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class = "content-section">
        <form method = "POST"> 
            {% csrf_token %}
            <fieldset class= "form-group"> 
                <legend class = "border-bottom mb-4"> Login Here </legend>
                {{ form| crispy }}
            </fieldset>
            <div class= "form-group"> 
                <button class= "btn btn-outline-info" type= "submit"> Login </button>
            </div> 
        </form> 
        <div class= "border-top pt-3"> 
            <small class = "text-muted">
                Need an account? <a class ="ml-2" href ="{% url 'register' %}"> Sign up now</a>  
            </small>   
        </div>
    </div>
{% endblock content %}  

users/templates/users/logout.html
{% extends "polling/admin/base.html" %}
{% block content %}
    <h2> You have been logged out </h2>    
    <div class= "border-top pt-3"> 
            <small class = "text-muted">
                <a href ="{% url 'login' %}"> Login Again </a>  
            </small>   
    </div>
    
{% endblock content %}  

users/templates/users/profile.html
{% extends "polling/admin/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
   
    <div class="content-section">
        <div class="media">
          <img class="rounded-circle account-img" src="{{ user.profile.image.url}}">
          <div class="media-body">
            <h2 class="account-heading"> {{ user.username }} </h2>
            <p class="text-secondary"> {{user.email}}</p>
          </div>
            <form method = "POST" enctype="multipart/form-data"> 
                {% csrf_token %}
                <fieldset class= "form-group"> 
                    <legend class = "border-bottom mb-4"> Profile Info </legend>
                    {{ u_form| crispy }}
                    {{ p_form| crispy }}
                </fieldset>
                <div class= "form-group"> 
                    <button class= "btn btn-outline-info" type= "submit"> Update </button>
                </div> 
            </form> 
        </div>
    </div>

{% endblock content %}  

users/templates/users/register.html
{% extends "polling/admin/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class = "content-section">
        <form method = "POST"> 
            {% csrf_token %}
            <fieldset class= "form-group"> 
                <legend class = "border-bottom mb-4"> Join Today </legend>
                {{ form| crispy }}
            </fieldset>
            <div class= "form-group"> 
                <button class= "btn btn-outline-info" type= "submit"> Sign up </button>
            </div> 
        </form> 
        <div class= "border-top pt-3"> 
            <small class = "text-muted">
                Already have an account? <a class ="ml-2" href =" {% url 'login' %}"> Sign in </a>  
            </small>   
        </div>
    </div>
{% endblock content %}  